# Generated by Django 5.0.1 on 2026-02-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
