# Generated by Django 5.0.1 on 2026-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_country_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Цвет"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Размер"
            ),
        ),
    ]
