# Generated by Django 5.0.1 on 2026-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_security_session_key_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cdek_tracking_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If set and status changes to Shipped, an email will be sent to the customer.",
                max_length=100,
                verbose_name="CDEK Tracking Number",
            ),
        ),
    ]
