# Generated by Django 5.0.1 on 2026-01-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(max_length=100, unique=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("confirming", "Confirming"),
                            ("confirmed", "Confirmed"),
                            ("sending", "Sending"),
                            ("partially_paid", "Partially Paid"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("expired", "Expired"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price_currency", models.CharField(default="usd", max_length=10)),
                (
                    "pay_amount",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "pay_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "pay_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
