# Generated by Django 5.0.1 on 2026-02-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_id",
            new_name="transaction_id",
        ),
    ]
