# Generated by Django 5.0.1 on 2026-07-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_color_orderitem_size"),
        ("payments", "0002_rename_payment_id_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Сумма",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="RUB",
                help_text="ISO-код валюты (RUB, USD, EUR, ...)",
                max_length=10,
                verbose_name="Валюта",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="ID платежа на стороне провайдера",
                max_length=255,
                verbose_name="Внешний ID",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Провайдер-специфичные данные (адрес крипто-кошелька, и т.д.)",
                verbose_name="Метаданные",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда платёж был подтверждён",
                null=True,
                verbose_name="Дата оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("nowpayments", "NowPayments"), ("yookassa", "YooKassa")],
                default="nowpayments",
                help_text="Платёжная система, через которую создан платёж",
                max_length=50,
                verbose_name="Провайдер",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="provider_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Оригинальный статус от платёжной системы",
                max_length=50,
                verbose_name="Статус провайдера",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="raw_response",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Полный ответ от платёжной системы (для дебага)",
                verbose_name="Сырой ответ API",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_address",
            field=models.CharField(
                blank=True,
                help_text="Устаревшее поле. Данные теперь в metadata.",
                max_length=255,
                null=True,
                verbose_name="[deprecated] Pay Address (NowPayments)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Устаревшее поле. Данные теперь в metadata.",
                max_digits=20,
                null=True,
                verbose_name="[deprecated] Pay Amount (NowPayments)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="pay_currency",
            field=models.CharField(
                blank=True,
                help_text="Устаревшее поле. Данные теперь в metadata.",
                max_length=10,
                null=True,
                verbose_name="[deprecated] Pay Currency (NowPayments)",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                blank=True,
                default="waiting",
                help_text="Устаревшее поле. Используйте status.",
                max_length=50,
                verbose_name="[deprecated] Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Устаревшее поле. Используйте amount.",
                max_digits=10,
                null=True,
                verbose_name="[deprecated] Price Amount",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="price_currency",
            field=models.CharField(
                blank=True,
                default="rub",
                help_text="Устаревшее поле. Используйте currency.",
                max_length=10,
                verbose_name="[deprecated] Price Currency",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Устаревшее поле. Используйте external_id.",
                max_length=255,
                verbose_name="[deprecated] Transaction ID",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["external_id"], name="payments_pa_externa_e9415f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="payments_pa_status_7ad4af_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["order", "status"], name="payments_pa_order_i_a76289_idx"
            ),
        ),
    ]
