# Generated by Django 5.0.1 on 2026-06-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_has_multiple_colors"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        help_text="Маленькое изображение, используемое как кнопка выбора цвета",
                        upload_to="variants/previews/%Y/%m/",
                        verbose_name="Превью цвета",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Оставьте пустым, чтобы использовать основную цену товара",
                        max_digits=10,
                        null=True,
                        verbose_name="Цена (переопределить)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цветовой вариант",
                "verbose_name_plural": "Цветовые варианты",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VariantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="variants/gallery/%Y/%m/", verbose_name="Изображение"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Alt-текст"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото варианта",
                "verbose_name_plural": "Фото варианта",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="В наличии"),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.size",
                        verbose_name="Размер",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="catalog.productvariant",
                        verbose_name="Вариант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер варианта",
                "verbose_name_plural": "Размеры варианта",
                "unique_together": {("variant", "size")},
            },
        ),
    ]
