# Generated by Django 5.0.1 on 2026-06-13 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productvariant_variantimage_variantsize"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="catalog.color",
                verbose_name="Цвет",
            ),
        ),
    ]
