# Generated by Django 5.0.1 on 2026-07-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productvariant_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_out",
            field=models.BooleanField(default=False, verbose_name="Sold Out"),
        ),
    ]
