# Generated by Django 5.0.1 on 2026-08-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_add_order_to_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sold_out",
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "В наличии"),
                    ("sold_out", "Распродано (Sold Out)"),
                    ("hidden", "Скрыто (Не отображать на сайте)"),
                ],
                default="available",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
