# Generated by Django 5.0.1 on 2026-08-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options_remove_product_available_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_multiple_colors",
        ),
    ]
