# Generated by Django 5.0.1 on 2026-08-08 19:19

from django.db import migrations


def copy_categories(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.all():
        if product.category:
            product.categories.add(product.category)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_categories_alter_product_category"),
    ]

    operations = [
        migrations.RunPython(copy_categories, reverse_code=migrations.RunPython.noop),
    ]
