# Generated by Django 5.0.1 on 2026-08-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_migrate_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
