# Generated by Django 5.0.1 on 2026-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_category_options_category_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="size",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="variantsize",
            options={
                "ordering": ["size__order", "size__id"],
                "verbose_name": "Размер варианта",
                "verbose_name_plural": "Размеры варианта",
            },
        ),
        migrations.AddField(
            model_name="size",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Порядок"
            ),
        ),
    ]
