# Generated by Django 5.0.1 on 2026-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_size_options_alter_variantsize_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="description_override",
            field=models.TextField(
                blank=True,
                help_text="Оставьте пустым, чтобы использовать основное описание товара",
                null=True,
                verbose_name="Описание (переопределить)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name_override",
            field=models.CharField(
                blank=True,
                help_text="Оставьте пустым, чтобы использовать основное название товара",
                max_length=200,
                null=True,
                verbose_name="Название (переопределить)",
            ),
        ),
    ]
