# Generated by Django 5.0.1 on 2026-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_productvariant_description_override_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="description_override",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="name_override",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="price_override",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание расцветки"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название расцветки"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
