# Generated by Django 5.0.1 on 2026-08-10 14:29

from django.db import migrations


def migrate_data(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    ProductVariant = apps.get_model('catalog', 'ProductVariant')
    ProductImage = apps.get_model('catalog', 'ProductImage')
    VariantImage = apps.get_model('catalog', 'VariantImage')
    VariantSize = apps.get_model('catalog', 'VariantSize')

    for product in Product.objects.all():
        variants = list(ProductVariant.objects.filter(product=product))
        
        # 1. Ensure at least one variant exists
        if not variants:
            variant = ProductVariant.objects.create(
                product=product,
                name=product.name,
                description=product.description,
                price=product.price
            )
            variants.append(variant)
            
            # Move images from ProductImage to VariantImage for the default variant
            for i, p_img in enumerate(ProductImage.objects.filter(product=product).order_by('id')):
                VariantImage.objects.create(
                    variant=variant,
                    image=p_img.image,
                    alt_text=p_img.alt_text,
                    order=i
                )
            
            # Move sizes from Product.sizes to VariantSize
            for p_size in product.sizes.all():
                VariantSize.objects.create(
                    variant=variant,
                    size=p_size,
                    available=True
                )
        else:
            # If variants exist, make sure they have a name/desc/price if they are empty
            for variant in variants:
                if not variant.name:
                    variant.name = product.name
                if not variant.description:
                    variant.description = product.description
                if not variant.price:
                    variant.price = product.price
                variant.save()

class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_remove_productvariant_description_override_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
    ]
