# Generated by Django 5.0.1 on 2026-08-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_migrate_product_to_variants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
