# Generated by Django 5.0.1 on 2026-08-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_remove_product_colors_remove_product_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Цветовой вариант",
                "verbose_name_plural": "Цветовые варианты",
            },
        ),
        migrations.AlterModelOptions(
            name="variantimage",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Фото варианта",
                "verbose_name_plural": "Фото варианта",
            },
        ),
    ]
